version: '3.8'

services:

  # Servicio de la API
  snake-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snake-game-container
    volumes:
      - .:/app
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      - app-network


  # Servicio de Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring
      - app-network

  # Servicio de Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
      - app-network

# Definir volúmenes para persistencia de datos
volumes:
  postgres_data:
  grafana-data:

# Definir redes
networks:
  app-network:
    driver: bridge
  monitoring:
    driver: bridge