global:
  scrape_interval: 1s  # Intervalo de recolección de métricas

scrape_configs:
  - job_name: 'api_container'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['snake-game-container:8000']